#!/usr/bin/env ruby

require 'spacefind'
require 'slop'
require 'term/ansicolor'

include Term::ANSIColor

opts = Slop.parse do |o|
  o.string '-d', '--dir', 'Search an alternate directory (default: CWD)'
  o.bool '-u', '--unlimited', 'Search all files (default: only *.{php,phtml} files)'
  o.bool '-q', '--quiet', 'Suppress all non-essential output'
  o.on '-h', '--help', 'Show this help message' do
    puts o
    exit
  end
  o.on '--version', 'Print version' do
    puts Spacefind::VERSION
    exit
  end
end

pattern = '**/*'
pattern = File.join(opts[:dir], pattern) unless opts[:dir].nil?
pattern += '.{php,phtml}' unless opts.unlimited?

puts "Searching #{pattern} for problems..." unless opts.quiet?

Dir.glob(pattern) do |f|
  next unless File.file?(f)
  problems = Spacefind.scan_for_problems(f)
  next if problems.empty?

  puts 'in ' + bold { f } + ':'
  problems.each do |p|
    puts "\t" + red { p.description }
  end
end

puts 'Done.' unless opts.quiet?
